default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'brett@dudo.io'
  domain: '503020.money www.502030.money'

  # in Rails.root, path to private key
  private_key: <%= ENV['CERT_KEYFILE'] %> #'config/certs/key/keyfile.pem'

  # in Rails.root, path where certificates
  # will be stored (on Heroku this variable is ignored)
  output_cert_dir: 'config/certs/certificate'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  challenge_dir_name: 'config/certs/challenge'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default